Vagrant.configure(2) do |config|
  config.vm.box = "gocd/gocd-demo"
  
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "2"
    vb.memory = "2048"
    #vb.customize ["modifyhd", "b4e44e75-5afc-467a-a8aa-5c21f3315d4a", "--resize", "8096"]
  end
end
